// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAsGaJga0KV4xtna94TfA9A8XbSAPJdWRE',
    appId: '1:614341341464:web:c815f9592b16bee62b6e6d',
    messagingSenderId: '614341341464',
    projectId: 'progresssofttask-f4bfe',
    authDomain: 'progresssofttask-f4bfe.firebaseapp.com',
    databaseURL: 'https://progresssofttask-f4bfe-default-rtdb.firebaseio.com',
    storageBucket: 'progresssofttask-f4bfe.appspot.com',
    measurementId: 'G-JBCCGCHGC0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLa8v7Iy50DEHNgkg6ZiVwqcKEQ1vRCrQ',
    appId: '1:614341341464:android:8d268b23b8f928652b6e6d',
    messagingSenderId: '614341341464',
    projectId: 'progresssofttask-f4bfe',
    databaseURL: 'https://progresssofttask-f4bfe-default-rtdb.firebaseio.com',
    storageBucket: 'progresssofttask-f4bfe.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANcSVCFQfkULATBsGRM3vu3ysQT5E39Hw',
    appId: '1:614341341464:ios:2b6e5e1292f07c042b6e6d',
    messagingSenderId: '614341341464',
    projectId: 'progresssofttask-f4bfe',
    databaseURL: 'https://progresssofttask-f4bfe-default-rtdb.firebaseio.com',
    storageBucket: 'progresssofttask-f4bfe.appspot.com',
    iosBundleId: 'com.example.taskProgresssoft',
  );
}
